name: 'announce-release-to-google-chat'
description: 'Announce Release to Google Chat'
author: 'andrewbrereton'
branding:
  icon: 'truck'
  color: 'blue'
inputs:
  webhook-url:
    description: 'Google Chat Webhook URL'
    required: true
runs:
  using: 'node20'
  main: 'dist/index.js'
