name: Test Custom Action

on:
  push:
    branches:
      - main

jobs:
  test_action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run announce-release-to-google-chat
        uses: ./ # Use the action in the root directory
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          webhook-url: ${{ secrets.WEBHOOK_URL }}
        id: announce_release_to_google_chat

      - name: Dump output
        env:
          CUSTOM_ACTION_OUTPUTS: ${{ toJson(steps.announce_release_to_google_chat.outputs) }}
        run: |
          echo "All outputs from announce_release_to_google_chat:"
          echo "$CUSTOM_ACTION_OUTPUTS" | jq .
